package br.com.sibela.tweetmood.constants

class AnimationConstants {

    companion object {
        const val AVARAGE_ACTIVITY_TRANSITION_TIME = 500L

        const val INTERMEDIATE_ANIMATION_DURATION = 1000L

        const val CONSTRAINT_SET_INTERMEDIATE_DURATION = INTERMEDIATE_ANIMATION_DURATION
        const val ANTICIPATE_OVERSHOOT_INTERPOLATOR_INTERMEDIATE_TENSION = 1.0f
        const val CONSTRAINT_SET_STARTING_DELAY = 1000L
        const val DISPLAY_TWEETS_DELAY = 500L

        const val SENTIMENT_BACKGROUND_COLOR_DELAY = 0L
        const val SENTIMENT_MESSAGE_DELAY = SENTIMENT_BACKGROUND_COLOR_DELAY + 1000
        const val SENTIMENT_IMAGE_DELAY = SENTIMENT_BACKGROUND_COLOR_DELAY + 1000

    }
}